name: Install Tomcat on EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
            uses: actions/checkout@v4

        - name: Setup SSH
            uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

        - name: Install Tomcat on EC2
            run: |
                ssh -o StrictHostKeyChecking=no ec2-user@<your-ec2-ip> <<EOF
                    sudo yum update -y
                    sudo yum install tomcat8 -y
                    sudo service tomcat8 start
                EOF
        - name: Create AMI
            run: |
                ssh -o StrictHostKeyChecking=no ec2-user@<your-ec2-ip> <<EOF
                        # The curl command is used to fetch the instance ID of the current EC2 instance from the metadata URL
                        INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
                        # The aws ec2 create-image command is used to create an AMI from the current EC2 instance
                        AMI_ID=$(aws ec2 create-image --instance-id $INSTANCE_ID --name "ubuntu8-tomcat-ami" --description "An Tomcat image." --no-reboot --query 'ImageId' --output text)
                        echo "AMI ID: $AMI_ID"
                EOF
        - name: Create EC2 instance from AMI
            run: |
                    ssh -o StrictHostKeyChecking=no ec2-user@<your-ec2-ip> <<EOF
                            # The aws ec2 run-instances command is used to launch a new EC2 instance from the AMI created in the previous step
                            INSTANCE_ID=$(aws ec2 run-instances --image-id $AMI_ID --count 1 --instance-type t2.micro --key-name MyKeyPair --security-group-ids sg-903004f8 --subnet-id subnet-6e7f829e --query 'Instances[0].InstanceId' --output text)
                            echo "New EC2 Instance ID: $INSTANCE_ID"
                    EOF

        - name: Deploy ELK stack on EC2
            run: |
                ssh -o StrictHostKeyChecking=no ec2-user@<your-ec2-ip> <<EOF
                    # Install Elasticsearch
                    sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
                    sudo tee /etc/yum.repos.d/elasticsearch.repo <<-EOF
                    [elasticsearch-7.x]
                    name=Elasticsearch repository for 7.x packages
                    baseurl=https://artifacts.elastic.co/packages/7.x/yum
                    gpgcheck=1
                    gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
                    enabled=1
                    autorefresh=1
                    type=rpm-md
                    EOF
                    sudo yum install elasticsearch -y
                    sudo systemctl start elasticsearch
                    sudo systemctl enable elasticsearch

                    # Install Logstash
                    sudo yum install logstash -y
                    sudo systemctl start logstash
                    sudo systemctl enable logstash

                    # Install Kibana
                    sudo yum install kibana -y
                    sudo systemctl start kibana
                    sudo systemctl enable kibana
                EOF
